# fly.toml app configuration file generated for lazy-tarot-translations on 2024-07-25T21:15:38+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lazy-tarot-translations'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
